service: web

plugins:
  - serverless-s3-sync
  - serverless-s3-cleaner
  - serverless-scriptable-plugin

package:
  patterns:
    - '!node_modules/**'
    - '!.serverless/**'
    - '!.build/**'

custom:
  project: ${file(../config.yml):project}
  baseName: ${self:custom.project}-${self:service}-${self:provider.stage}
  
  scriptHooks:
    after:aws:deploy:deploy:updateStack:
      - generateConfigFile.js
      - yarn run build

  s3Sync:
    - bucketNameKey: WebsiteBucket
      localDir: build
  
  serverless-s3-cleaner:
    buckets:
      - ${cf:${self:custom.baseName}.VideoChatWebsiteBucketName, ''}

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  stackName: ${self:custom.baseName}
  stackTags: ${file(../config.yml):tags}
  deploymentBucket:
    name: ${cf:${self:custom.project}-common-${self:provider.stage}.ServerlessDeploymentBucketName}

resources:
  Resources:

    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        WebsiteConfiguration:
          IndexDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

  Outputs:
    WebsiteBucketName:
      Value: !Ref WebsiteBucket
